#!/usr/bin/env bash
# =============================================================================
# GTKWave Waveform Capture Script
# =============================================================================
# Opens the Verilator FST waveform in GTKWave with a pre-configured view
# showing the ITCH parser decoding an Add Order message. Can optionally
# take a screenshot for documentation.
#
# Prerequisites:
#   - GTKWave installed (sudo apt-get install gtkwave)
#   - Verilator simulation already run (make verilator_run)
#   - For screenshots: xdotool + imagemagick (headless capture)
#
# Usage:
#   ./sim/scripts/capture_waveform.sh                  # Open interactively
#   ./sim/scripts/capture_waveform.sh --screenshot     # Save to docs/images/
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

FST_FILE="$PROJECT_ROOT/sim/verilator/itch_parser.fst"
SAVE_FILE="$PROJECT_ROOT/sim/scripts/itch_parser.gtkw"
SCREENSHOT_DIR="$PROJECT_ROOT/docs/images"
SCREENSHOT_PATH="$SCREENSHOT_DIR/gtkwave_itch_parser.png"

# ---------------------------------------------------------------------------
# Check prerequisites
# ---------------------------------------------------------------------------
if [ ! -f "$FST_FILE" ]; then
    echo "ERROR: Waveform file not found: $FST_FILE"
    echo "Run 'make verilator_run' first to generate the waveform."
    exit 1
fi

if ! command -v gtkwave &> /dev/null; then
    echo "ERROR: GTKWave not found. Install with:"
    echo "  sudo apt-get install gtkwave"
    exit 1
fi

# ---------------------------------------------------------------------------
# Generate GTKWave save file (.gtkw)
# ---------------------------------------------------------------------------
# This pre-configures the view to show the most interesting signals:
# the FSM state, AXI-Stream handshake, and parsed output fields.
cat > "$SAVE_FILE" << 'GTKW_EOF'
[*]
[*] GTKWave Save File — ITCH Parser Waveform View
[*] Auto-generated by capture_waveform.sh
[*]
[dumpfile] itch_parser.fst
[timestart] 0
[size] 1400 800
[pos] -1 -1

[sst_expanded] 1

*-1.000000 90 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

[treeopen] TOP.
[treeopen] TOP.itch_parser.

@28
TOP.itch_parser.clk
TOP.itch_parser.rst_n

@22
TOP.itch_parser.state[2:0]

@28
TOP.itch_parser.s_axis_tvalid
TOP.itch_parser.s_axis_tready
TOP.itch_parser.s_axis_tlast

@22
TOP.itch_parser.s_axis_tdata[63:0]

@22
TOP.itch_parser.byte_counter[5:0]

@28
TOP.itch_parser.order_out.valid

@22
TOP.itch_parser.order_out.order_ref[63:0]
TOP.itch_parser.order_out.stock[63:0]
TOP.itch_parser.order_out.price[31:0]
TOP.itch_parser.order_out.shares[31:0]

@28
TOP.itch_parser.order_out.side

@22
TOP.itch_parser.msg_count[63:0]
TOP.itch_parser.add_order_count[63:0]

[pattern_trace] 1
[pattern_trace] 0
GTKW_EOF

echo "GTKWave save file written: $SAVE_FILE"

# ---------------------------------------------------------------------------
# Open GTKWave or take a screenshot
# ---------------------------------------------------------------------------
if [ "${1:-}" = "--screenshot" ]; then
    mkdir -p "$SCREENSHOT_DIR"

    echo "Taking screenshot (requires X display)..."

    if [ -z "${DISPLAY:-}" ]; then
        echo "WARNING: No DISPLAY set. Attempting with Xvfb (virtual framebuffer)..."
        if command -v xvfb-run &> /dev/null; then
            xvfb-run --auto-servernum --server-args='-screen 0 1400x800x24' \
                gtkwave "$FST_FILE" --save="$SAVE_FILE" --script=<(echo "
                    gtkwave::setZoomFactor -3
                    gtkwave::nop
                ") &
            GTKWAVE_PID=$!
            sleep 3

            if command -v import &> /dev/null; then
                import -window root "$SCREENSHOT_PATH"
                echo "Screenshot saved: $SCREENSHOT_PATH"
            else
                echo "WARNING: ImageMagick 'import' not found. Install with:"
                echo "  sudo apt-get install imagemagick"
            fi

            kill $GTKWAVE_PID 2>/dev/null || true
        else
            echo "WARNING: xvfb-run not found. Install with:"
            echo "  sudo apt-get install xvfb"
            echo ""
            echo "Manual alternative: open GTKWave on a machine with a display:"
            echo "  gtkwave $FST_FILE --save=$SAVE_FILE"
            echo "  Then take a screenshot and save it to: $SCREENSHOT_PATH"
        fi
    else
        gtkwave "$FST_FILE" --save="$SAVE_FILE" &
        GTKWAVE_PID=$!
        sleep 3

        if command -v import &> /dev/null; then
            import -window root "$SCREENSHOT_PATH"
            echo "Screenshot saved: $SCREENSHOT_PATH"
        fi

        kill $GTKWAVE_PID 2>/dev/null || true
    fi
else
    echo "Opening GTKWave..."
    echo "  Waveform: $FST_FILE"
    echo "  Config:   $SAVE_FILE"
    gtkwave "$FST_FILE" --save="$SAVE_FILE" &
    echo "GTKWave launched (PID: $!)"
fi
